/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChangeStatusParams,
  Delete7Params,
  DeptDTO,
  DictDataDTO,
  DictTypeDTO,
  List1Params,
  ListByDictTypeParams,
  LoginRequest,
  MenuDTO,
  Page1Params,
  Page2Params,
  Page3Params,
  PageParams,
  PostDTO,
  RCaptchaVO,
  RDictTypeVO,
  RListDictDataVO,
  RListDictTypeVO,
  RListLong,
  RListSysDept,
  RListSysMenu,
  RListSysPost,
  RListSysRole,
  RLoginVO,
  RLong,
  ROssResult,
  RPageResultDictTypeVO,
  RPageResultSysOperLog,
  RPageResultSysPost,
  RPageResultSysRole,
  RPageResultSysUser,
  RSysDept,
  RSysMenu,
  RSysPost,
  RSysRole,
  RSysUser,
  RUserInfo,
  RVoid,
  RoleDTO,
  UploadBody,
  UserDTO
} from '../models';

import { customFetch } from '../utils/api-mutator';



  export const getAiPermRBACAPI = () => {
/**
 * @summary 根据ID查询用户
 */
const getById = (
    id: number,
 ) => {
      return customFetch<RSysUser>(
      {url: `/system/user/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新用户
 */
const update = (
    id: number,
    userDTO: UserDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/user/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userDTO
    },
      );
    }
  
/**
 * @summary 删除用户
 */
const _delete = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/user/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 修改用户状态
 */
const changeStatus = (
    id: number,
    params: ChangeStatusParams,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/user/${id}/status`, method: 'PUT',
        params
    },
      );
    }
  
/**
 * @summary 重置用户密码
 */
const resetPassword = (
    id: number,
    userDTO: UserDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/user/${id}/reset-password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userDTO
    },
      );
    }
  
/**
 * @summary 根据ID查询角色
 */
const getById1 = (
    id: number,
 ) => {
      return customFetch<RSysRole>(
      {url: `/system/role/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新角色
 */
const update1 = (
    id: number,
    roleDTO: RoleDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/role/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roleDTO
    },
      );
    }
  
/**
 * @summary 删除角色
 */
const delete1 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/role/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 根据ID查询岗位
 */
const getById2 = (
    id: number,
 ) => {
      return customFetch<RSysPost>(
      {url: `/system/post/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新岗位
 */
const update2 = (
    id: number,
    postDTO: PostDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/post/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: postDTO
    },
      );
    }
  
/**
 * @summary 删除岗位
 */
const delete2 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/post/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 根据ID查询菜单
 */
const getById3 = (
    id: number,
 ) => {
      return customFetch<RSysMenu>(
      {url: `/system/menu/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新菜单
 */
const update3 = (
    id: number,
    menuDTO: MenuDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/menu/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: menuDTO
    },
      );
    }
  
/**
 * @summary 删除菜单
 */
const delete3 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/menu/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 查询字典类型详情
 */
const detail = (
    id: number,
 ) => {
      return customFetch<RDictTypeVO>(
      {url: `/system/dict/type/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新字典类型
 */
const update4 = (
    id: number,
    dictTypeDTO: DictTypeDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dict/type/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dictTypeDTO
    },
      );
    }
  
/**
 * @summary 删除字典类型
 */
const delete4 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dict/type/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 更新字典数据
 */
const update5 = (
    id: number,
    dictDataDTO: DictDataDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dict/data/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dictDataDTO
    },
      );
    }
  
/**
 * @summary 删除字典数据
 */
const delete5 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dict/data/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 根据ID查询部门
 */
const getById4 = (
    id: number,
 ) => {
      return customFetch<RSysDept>(
      {url: `/system/dept/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新部门
 */
const update6 = (
    id: number,
    deptDTO: DeptDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dept/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: deptDTO
    },
      );
    }
  
/**
 * @summary 删除部门
 */
const delete6 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dept/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 分页查询用户列表
 */
const page = (
    params: PageParams,
 ) => {
      return customFetch<RPageResultSysUser>(
      {url: `/system/user`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 创建用户
 */
const create = (
    userDTO: UserDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userDTO
    },
      );
    }
  
/**
 * @summary 分页查询角色列表
 */
const page1 = (
    params: Page1Params,
 ) => {
      return customFetch<RPageResultSysRole>(
      {url: `/system/role`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 创建角色
 */
const create1 = (
    roleDTO: RoleDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roleDTO
    },
      );
    }
  
/**
 * @summary 获取角色的菜单ID列表
 */
const getRoleMenus = (
    id: number,
 ) => {
      return customFetch<RListLong>(
      {url: `/system/role/${id}/menus`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 分配角色菜单
 */
const assignMenus = (
    id: number,
    assignMenusBody: number[],
 ) => {
      return customFetch<RVoid>(
      {url: `/system/role/${id}/menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignMenusBody
    },
      );
    }
  
/**
 * @summary 分页查询岗位列表
 */
const page2 = (
    params: Page2Params,
 ) => {
      return customFetch<RPageResultSysPost>(
      {url: `/system/post`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 创建岗位
 */
const create2 = (
    postDTO: PostDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/post`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postDTO
    },
      );
    }
  
/**
 * @summary 查询所有菜单
 */
const list = (
    
 ) => {
      return customFetch<RListSysMenu>(
      {url: `/system/menu`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 创建菜单
 */
const create3 = (
    menuDTO: MenuDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/menu`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: menuDTO
    },
      );
    }
  
/**
 * @summary 分页查询字典类型
 */
const list1 = (
    params: List1Params,
 ) => {
      return customFetch<RPageResultDictTypeVO>(
      {url: `/system/dict/type`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 创建字典类型
 */
const create4 = (
    dictTypeDTO: DictTypeDTO,
 ) => {
      return customFetch<RLong>(
      {url: `/system/dict/type`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dictTypeDTO
    },
      );
    }
  
/**
 * @summary 创建字典数据
 */
const create5 = (
    dictDataDTO: DictDataDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dict/data`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dictDataDTO
    },
      );
    }
  
/**
 * @summary 查询所有部门
 */
const list2 = (
    
 ) => {
      return customFetch<RListSysDept>(
      {url: `/system/dept`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 创建部门
 */
const create6 = (
    deptDTO: DeptDTO,
 ) => {
      return customFetch<RVoid>(
      {url: `/system/dept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deptDTO
    },
      );
    }
  
/**
 * @summary 上传文件
 */
const upload = (
    uploadBody: UploadBody,
 ) => {
      return customFetch<ROssResult>(
      {url: `/oss/upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadBody
    },
      );
    }
  
/**
 * @summary 登出
 */
const logout = (
    
 ) => {
      return customFetch<RVoid>(
      {url: `/auth/logout`, method: 'POST'
    },
      );
    }
  
/**
 * @summary 登录
 */
const login = (
    loginRequest: LoginRequest,
 ) => {
      return customFetch<RLoginVO>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
/**
 * @summary 查询所有角色
 */
const list3 = (
    
 ) => {
      return customFetch<RListSysRole>(
      {url: `/system/role/all`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 查询所有岗位
 */
const list4 = (
    
 ) => {
      return customFetch<RListSysPost>(
      {url: `/system/post/all`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 查询菜单树
 */
const tree = (
    
 ) => {
      return customFetch<RListSysMenu>(
      {url: `/system/menu/tree`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 查询子菜单列表
 */
const getChildren = (
    parentId: number,
 ) => {
      return customFetch<RListSysMenu>(
      {url: `/system/menu/children/${parentId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 查询所有启用的字典类型
 */
const all = (
    
 ) => {
      return customFetch<RListDictTypeVO>(
      {url: `/system/dict/type/all`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 根据字典类型查询字典数据
 */
const listByDictType = (
    params: ListByDictTypeParams,
 ) => {
      return customFetch<RListDictDataVO>(
      {url: `/system/dict/data/list`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 查询部门树
 */
const tree1 = (
    
 ) => {
      return customFetch<RListSysDept>(
      {url: `/system/dept/tree`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 查询子部门列表
 */
const getChildren1 = (
    parentId: number,
 ) => {
      return customFetch<RListSysDept>(
      {url: `/system/dept/children/${parentId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 分页查询操作日志
 */
const page3 = (
    params?: Page3Params,
 ) => {
      return customFetch<RPageResultSysOperLog>(
      {url: `/log/oper`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 获取当前用户信息
 */
const userInfo = (
    
 ) => {
      return customFetch<RUserInfo>(
      {url: `/auth/user-info`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 获取验证码
 */
const captcha = (
    
 ) => {
      return customFetch<RCaptchaVO>(
      {url: `/auth/captcha`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 删除文件
 */
const delete7 = (
    params: Delete7Params,
 ) => {
      return customFetch<RVoid>(
      {url: `/oss`, method: 'DELETE',
        params
    },
      );
    }
  
/**
 * @summary 删除操作日志
 */
const delete8 = (
    id: number,
 ) => {
      return customFetch<RVoid>(
      {url: `/log/oper/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 清空操作日志
 */
const clean = (
    
 ) => {
      return customFetch<RVoid>(
      {url: `/log/oper/clean`, method: 'DELETE'
    },
      );
    }
  
return {getById,update,_delete,changeStatus,resetPassword,getById1,update1,delete1,getById2,update2,delete2,getById3,update3,delete3,detail,update4,delete4,update5,delete5,getById4,update6,delete6,page,create,page1,create1,getRoleMenus,assignMenus,page2,create2,list,create3,list1,create4,create5,list2,create6,upload,logout,login,list3,list4,tree,getChildren,all,listByDictType,tree1,getChildren1,page3,userInfo,captcha,delete7,delete8,clean}};
export type GetByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getById']>>>
export type UpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update']>>>
export type _DeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['_delete']>>>
export type ChangeStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['changeStatus']>>>
export type ResetPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['resetPassword']>>>
export type GetById1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getById1']>>>
export type Update1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update1']>>>
export type Delete1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete1']>>>
export type GetById2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getById2']>>>
export type Update2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update2']>>>
export type Delete2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete2']>>>
export type GetById3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getById3']>>>
export type Update3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update3']>>>
export type Delete3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete3']>>>
export type DetailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['detail']>>>
export type Update4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update4']>>>
export type Delete4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete4']>>>
export type Update5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update5']>>>
export type Delete5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete5']>>>
export type GetById4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getById4']>>>
export type Update6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['update6']>>>
export type Delete6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete6']>>>
export type PageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['page']>>>
export type CreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create']>>>
export type Page1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['page1']>>>
export type Create1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create1']>>>
export type GetRoleMenusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getRoleMenus']>>>
export type AssignMenusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['assignMenus']>>>
export type Page2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['page2']>>>
export type Create2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create2']>>>
export type ListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['list']>>>
export type Create3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create3']>>>
export type List1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['list1']>>>
export type Create4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create4']>>>
export type Create5Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create5']>>>
export type List2Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['list2']>>>
export type Create6Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['create6']>>>
export type UploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['upload']>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['logout']>>>
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['login']>>>
export type List3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['list3']>>>
export type List4Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['list4']>>>
export type TreeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['tree']>>>
export type GetChildrenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getChildren']>>>
export type AllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['all']>>>
export type ListByDictTypeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['listByDictType']>>>
export type Tree1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['tree1']>>>
export type GetChildren1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['getChildren1']>>>
export type Page3Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['page3']>>>
export type UserInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['userInfo']>>>
export type CaptchaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['captcha']>>>
export type Delete7Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete7']>>>
export type Delete8Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['delete8']>>>
export type CleanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAiPermRBACAPI>['clean']>>>
