/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 验证码响应
 */
export interface CaptchaVO {
  /** 验证码Key */
  captchaKey?: string;
  /** 验证码图片（Base64） */
  captchaImage?: string;
}
