/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 系统配置响应VO
 */
export interface ConfigVO {
  /** 配置ID */
  id?: number;
  /** 配置键 */
  configKey?: string;
  /** 配置值 */
  configValue?: string;
  /** 配置类型 */
  configType?: string;
  /** 备注 */
  remark?: string;
  /** 创建时间 */
  createTime?: string;
}
