/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 系统配置数据
 */
export interface ConfigDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 配置键
   * @minLength 0
   * @maxLength 100
   */
  configKey: string;
  /** 配置值 */
  configValue?: string;
  /**
   * 配置类型
   * @minLength 0
   * @maxLength 50
   */
  configType?: string;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
