/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 部门数据
 */
export interface DeptDTO {
  /**
   * 部门名称
   * @minLength 0
   * @maxLength 100
   */
  deptName: string;
  /** 父部门ID（0为根部门） */
  parentId?: number;
  /** 显示顺序 */
  sort?: number;
  /**
   * 负责人
   * @minLength 0
   * @maxLength 50
   */
  leader?: string;
  /**
   * 联系电话
   * @minLength 0
   * @maxLength 20
   */
  phone?: string;
  /**
   * 邮箱
   * @minLength 0
   * @maxLength 100
   */
  email?: string;
  /** 部门状态（0=正常，1=停用） */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
