/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 字典类型响应VO
 */
export interface DictTypeVO {
  /** 字典类型ID */
  id?: number;
  /** 字典名称 */
  dictName?: string;
  /** 字典类型标识 */
  dictType?: string;
  /** 状态：0-禁用 1-启用 */
  status?: number;
  /** 备注 */
  remark?: string;
  /** 创建时间 */
  createTime?: string;
}
