/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 字典数据响应VO
 */
export interface DictDataVO {
  /** 字典数据ID */
  id?: number;
  /** 字典类型 */
  dictType?: string;
  /** 字典标签（显示值） */
  dictLabel?: string;
  /** 字典键值（存储值） */
  dictValue?: string;
  /** 排序 */
  sort?: number;
  /** 状态：0-禁用 1-启用 */
  status?: number;
  /** 备注 */
  remark?: string;
}
