/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 字典类型数据
 */
export interface DictTypeDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 字典名称
   * @minLength 0
   * @maxLength 100
   */
  dictName: string;
  /**
   * 字典类型
   * @minLength 0
   * @maxLength 100
   */
  dictType: string;
  /** 状态：0-禁用 1-启用 */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
