/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

export * from './captchaVO';
export * from './changeStatusParams';
export * from './delete7Params';
export * from './deptDTO';
export * from './dictDataDTO';
export * from './dictDataVO';
export * from './dictTypeDTO';
export * from './dictTypeVO';
export * from './list1Params';
export * from './listByDictTypeParams';
export * from './loginRequest';
export * from './loginVO';
export * from './menuDTO';
export * from './ossResult';
export * from './page1Params';
export * from './page2Params';
export * from './page3Params';
export * from './pageParams';
export * from './pageResultDictTypeVO';
export * from './pageResultSysOperLog';
export * from './pageResultSysPost';
export * from './pageResultSysRole';
export * from './pageResultSysUser';
export * from './postDTO';
export * from './rCaptchaVO';
export * from './rDictTypeVO';
export * from './rListDictDataVO';
export * from './rListDictTypeVO';
export * from './rListLong';
export * from './rListSysDept';
export * from './rListSysMenu';
export * from './rListSysPost';
export * from './rListSysRole';
export * from './rLoginVO';
export * from './rLong';
export * from './rOssResult';
export * from './rPageResultDictTypeVO';
export * from './rPageResultSysOperLog';
export * from './rPageResultSysPost';
export * from './rPageResultSysRole';
export * from './rPageResultSysUser';
export * from './rSysDept';
export * from './rSysMenu';
export * from './rSysPost';
export * from './rSysRole';
export * from './rSysUser';
export * from './rUserInfo';
export * from './rVoid';
export * from './rVoidData';
export * from './roleDTO';
export * from './sysDept';
export * from './sysMenu';
export * from './sysOperLog';
export * from './sysPost';
export * from './sysRole';
export * from './sysUser';
export * from './uploadBody';
export * from './userDTO';
export * from './userInfo';