/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 定时任务数据
 */
export interface JobDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 任务名称
   * @minLength 0
   * @maxLength 100
   */
  jobName: string;
  /**
   * 任务分组
   * @minLength 0
   * @maxLength 50
   */
  jobGroup?: string;
  /**
   * Cron表达式
   * @minLength 0
   * @maxLength 100
   */
  cronExpression: string;
  /**
   * 执行类
   * @minLength 0
   * @maxLength 200
   */
  beanClass: string;
  /** 状态：0-暂停 1-运行 */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
