/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 定时任务响应VO
 */
export interface JobVO {
  /** 任务ID */
  id?: number;
  /** 任务名称 */
  jobName?: string;
  /** 任务分组 */
  jobGroup?: string;
  /** Cron表达式 */
  cronExpression?: string;
  /** 执行类 */
  beanClass?: string;
  /** 状态：0-暂停 1-运行 */
  status?: number;
  /** 备注 */
  remark?: string;
  /** 创建时间 */
  createTime?: string;
}
