/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */
import type { UserInfo } from './userInfo';

/**
 * 登录响应
 */
export interface LoginVO {
  /** 访问令牌 */
  token?: string;
  /** 用户信息 */
  userInfo?: UserInfo;
}
