/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 登录请求
 */
export interface LoginRequest {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 验证码 */
  captcha?: string;
  /** 验证码Key */
  captchaKey?: string;
}
