/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 菜单数据
 */
export interface MenuDTO {
  /**
   * 菜单名称
   * @minLength 0
   * @maxLength 100
   */
  menuName: string;
  /** 父菜单ID（0为根菜单） */
  parentId?: number;
  /** 菜单类型（M=目录，C=菜单，F=按钮） */
  menuType: string;
  /** 显示顺序 */
  sort?: number;
  /**
   * 路由地址
   * @minLength 0
   * @maxLength 200
   */
  path?: string;
  /**
   * 组件路径
   * @minLength 0
   * @maxLength 200
   */
  component?: string;
  /**
   * 权限标识（按钮用，如 system:user:add）
   * @minLength 0
   * @maxLength 100
   */
  perms?: string;
  /**
   * 菜单图标
   * @minLength 0
   * @maxLength 100
   */
  icon?: string;
  /** 是否为外链（0=否，1=是） */
  isExternal?: number;
  /** 是否缓存（0=不缓存，1=缓存） */
  isCache?: number;
  /** 是否显示（0=隐藏，1=显示） */
  visible?: number;
  /** 菜单状态（0=正常，1=停用） */
  status?: number;
  /**
   * 权限标识
   * @minLength 0
   * @maxLength 100
   */
  permission?: string;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
