/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 消息响应VO
 */
export interface MessageVO {
  /** ID */
  id?: number;
  /** 发送人ID */
  senderId?: number;
  /** 发送人名称 */
  senderName?: string;
  /** 接收人ID */
  receiverId?: number;
  /** 标题 */
  title?: string;
  /** 内容 */
  content?: string;
  /** 是否已读：0-未读 1-已读 */
  isRead?: number;
  /** 阅读时间 */
  readTime?: string;
  /** 创建时间 */
  createTime?: string;
}
