/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 消息数据
 */
export interface MessageDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /** 接收人ID */
  receiverId: number;
  /**
   * 标题
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /** 内容 */
  content?: string;
  /** 是否已读：0-未读 1-已读 */
  isRead?: number;
  /** 消息ID列表（用于批量已读） */
  ids?: number[];
}
