/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 公告通知数据
 */
export interface NoticeDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 标题
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /** 内容 */
  content?: string;
  /** 类型：1-通知 2-公告 */
  type?: number;
  /** 状态：0-草稿 1-发布 */
  status?: number;
}
