/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */
import type { JobVO } from './jobVO';

/**
 * 分页结果
 */
export interface PageResultJobVO {
  /** 总记录数 */
  total?: number;
  /** 数据列表 */
  list?: JobVO[];
  /** 当前页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
  /** 总页数 */
  pages?: number;
}
