/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 岗位数据
 */
export interface PostDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 岗位名称
   * @minLength 0
   * @maxLength 100
   */
  postName: string;
  /**
   * 岗位编码
   * @minLength 0
   * @maxLength 100
   */
  postCode: string;
  /** 显示顺序 */
  sort?: number;
  /** 岗位状态（0=正常，1=停用） */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
}
