/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 角色数据
 */
export interface RoleDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 角色名称
   * @minLength 0
   * @maxLength 100
   */
  roleName: string;
  /**
   * 角色编码
   * @minLength 0
   * @maxLength 100
   */
  roleCode: string;
  /** 显示顺序 */
  sort?: number;
  /** 角色状态（0=正常，1=停用） */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
  /** 角色ID（用于分配菜单） */
  roleId?: number;
  /** 菜单ID列表 */
  menuIds?: number[];
}
