/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */
import type { PageResultConfigVO } from './pageResultConfigVO';

/**
 * 统一返回结果
 */
export interface RPageResultConfigVO {
  /** 状态码 */
  code?: number;
  /** 返回消息 */
  message?: string;
  /** 返回数据 */
  data?: PageResultConfigVO;
  success?: boolean;
}
