/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

export interface SysDept {
  id?: number;
  createTime?: string;
  updateTime?: string;
  createBy?: string;
  updateBy?: string;
  deleted?: number;
  version?: number;
  deptName?: string;
  parentId?: number;
  sort?: number;
  leader?: string;
  phone?: string;
  email?: string;
  status?: number;
  remark?: string;
  children?: SysDept[];
}
