/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

export interface SysOperLog {
  id?: number;
  title?: string;
  operType?: number;
  method?: string;
  requestMethod?: string;
  operUrl?: string;
  operIp?: string;
  operParam?: string;
  jsonResult?: string;
  status?: number;
  errorMsg?: string;
  costTime?: number;
  operUser?: string;
  operName?: string;
  createTime?: string;
}
