/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

export interface SysUser {
  id?: number;
  createTime?: string;
  updateTime?: string;
  createBy?: string;
  updateBy?: string;
  deleted?: number;
  version?: number;
  username?: string;
  nickname?: string;
  realName?: string;
  email?: string;
  phone?: string;
  gender?: number;
  avatar?: string;
  deptId?: number;
  postId?: number;
  isAdmin?: number;
  status?: number;
  remark?: string;
  lastLoginIp?: string;
  lastLoginTime?: string;
}
