/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AiPerm RBAC权限系统API
 * 基于Spring Boot 3 + Sa-Token + MyBatis-Plus的RBAC权限管理系统
 * OpenAPI spec version: 1.0.0
 */

/**
 * 用户数据
 */
export interface UserDTO {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
  /**
   * 用户名
   * @minLength 0
   * @maxLength 50
   */
  username: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /**
   * 昵称
   * @minLength 0
   * @maxLength 50
   */
  nickname?: string;
  /**
   * 真实姓名
   * @minLength 0
   * @maxLength 50
   */
  realName?: string;
  /**
   * 用户邮箱
   * @minLength 0
   * @maxLength 100
   */
  email?: string;
  /**
   * 手机号码
   * @minLength 0
   * @maxLength 20
   */
  phone?: string;
  /** 用户性别（0=未知，1=男，2=女） */
  gender?: number;
  /**
   * 头像地址
   * @minLength 0
   * @maxLength 500
   */
  avatar?: string;
  /** 部门ID */
  deptId?: number;
  /** 岗位ID */
  postId?: number;
  /** 用户状态（0=正常，1=停用） */
  status?: number;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   */
  remark?: string;
  /** 新密码（重置密码用） */
  newPassword?: string;
}
